"""initial analytics schema

Revision ID: c89eb6b09369
Revises:
Create Date: 2026-10-01 22:59:46.843495
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c89eb6b09369"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("school", sa.String(length=160), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("height_inches", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("weight_lbs", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("position_guard", sa.Boolean(), nullable=False),
        sa.Column("position_forward", sa.Boolean(), nullable=False),
        sa.Column("position_center", sa.Boolean(), nullable=False),
        sa.Column("from_year", sa.Integer(), nullable=True),
        sa.Column("to_year", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("player_id"),
    )
    op.create_index("ix_players_name", "players", ["last_name", "first_name"], unique=False)
    op.create_table(
        "teams",
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("team_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "games",
        sa.Column("game_id", sa.String(length=16), nullable=False),
        sa.Column("season_id", sa.String(length=10), nullable=False),
        sa.Column("tipoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("game_type", sa.String(length=40), nullable=False),
        sa.Column("home_team_id", sa.BigInteger(), nullable=False),
        sa.Column("away_team_id", sa.BigInteger(), nullable=False),
        sa.Column("home_score", sa.SmallInteger(), nullable=False),
        sa.Column("away_score", sa.SmallInteger(), nullable=False),
        sa.Column("winner_team_id", sa.BigInteger(), nullable=False),
        sa.Column("attendance", sa.Integer(), nullable=True),
        sa.Column("arena_name", sa.String(length=160), nullable=True),
        sa.CheckConstraint(
            "(home_score > away_score AND winner_team_id = home_team_id) OR "
            "(away_score > home_score AND winner_team_id = away_team_id)",
            name="ck_games_winner_matches_score",
        ),
        sa.CheckConstraint("home_score <> away_score", name="ck_games_no_ties"),
        sa.CheckConstraint(
            "home_score >= 0 AND away_score >= 0", name="ck_games_nonnegative_score"
        ),
        sa.CheckConstraint("home_team_id <> away_team_id", name="ck_games_distinct_teams"),
        sa.CheckConstraint(
            "winner_team_id IN (home_team_id, away_team_id)", name="ck_games_winner_participated"
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.team_id"],
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_index("ix_games_away_team_date", "games", ["away_team_id", "game_date"], unique=False)
    op.create_index(op.f("ix_games_game_date"), "games", ["game_date"], unique=False)
    op.create_index(op.f("ix_games_game_type"), "games", ["game_type"], unique=False)
    op.create_index("ix_games_home_team_date", "games", ["home_team_id", "game_date"], unique=False)
    op.create_index(op.f("ix_games_season_id"), "games", ["season_id"], unique=False)
    op.create_index(
        "ix_games_season_type_date",
        "games",
        ["season_id", "game_type", "game_date", "game_id"],
        unique=False,
    )
    op.create_table(
        "team_game_stats",
        sa.Column("game_id", sa.String(length=16), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("opponent_team_id", sa.BigInteger(), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("team_score", sa.SmallInteger(), nullable=False),
        sa.Column("opponent_score", sa.SmallInteger(), nullable=False),
        sa.Column("assists", sa.SmallInteger(), nullable=False),
        sa.Column("blocks", sa.SmallInteger(), nullable=False),
        sa.Column("steals", sa.SmallInteger(), nullable=False),
        sa.Column("field_goals_attempted", sa.SmallInteger(), nullable=False),
        sa.Column("field_goals_made", sa.SmallInteger(), nullable=False),
        sa.Column("field_goal_percentage", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("three_pointers_attempted", sa.SmallInteger(), nullable=False),
        sa.Column("three_pointers_made", sa.SmallInteger(), nullable=False),
        sa.Column("three_point_percentage", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("free_throws_attempted", sa.SmallInteger(), nullable=False),
        sa.Column("free_throws_made", sa.SmallInteger(), nullable=False),
        sa.Column("free_throw_percentage", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("defensive_rebounds", sa.SmallInteger(), nullable=False),
        sa.Column("offensive_rebounds", sa.SmallInteger(), nullable=False),
        sa.Column("total_rebounds", sa.SmallInteger(), nullable=False),
        sa.Column("personal_fouls", sa.SmallInteger(), nullable=False),
        sa.Column("turnovers", sa.SmallInteger(), nullable=False),
        sa.Column("plus_minus", sa.SmallInteger(), nullable=False),
        sa.Column("minutes_seconds", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("field_goal_percentage BETWEEN 0 AND 1", name="ck_team_stats_fg_pct"),
        sa.CheckConstraint(
            "field_goals_made BETWEEN 0 AND field_goals_attempted", name="ck_team_stats_fg_counts"
        ),
        sa.CheckConstraint("free_throw_percentage BETWEEN 0 AND 1", name="ck_team_stats_ft_pct"),
        sa.CheckConstraint(
            "free_throws_made BETWEEN 0 AND free_throws_attempted", name="ck_team_stats_ft_counts"
        ),
        sa.CheckConstraint("minutes_seconds > 0", name="ck_team_stats_minutes"),
        sa.CheckConstraint("plus_minus = team_score - opponent_score", name="ck_team_stats_margin"),
        sa.CheckConstraint("team_id <> opponent_team_id", name="ck_team_stats_distinct_teams"),
        sa.CheckConstraint("team_score >= 0 AND opponent_score >= 0", name="ck_team_stats_score"),
        sa.CheckConstraint("three_point_percentage BETWEEN 0 AND 1", name="ck_team_stats_3p_pct"),
        sa.CheckConstraint(
            "three_pointers_made BETWEEN 0 AND three_pointers_attempted",
            name="ck_team_stats_3p_counts",
        ),
        sa.CheckConstraint(
            "total_rebounds = offensive_rebounds + defensive_rebounds",
            name="ck_team_stats_rebounds",
        ),
        sa.CheckConstraint("won = (team_score > opponent_score)", name="ck_team_stats_win"),
        sa.ForeignKeyConstraint(["game_id"], ["games.game_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["opponent_team_id"],
            ["teams.team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.team_id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "team_id"),
    )
    op.create_index(
        "ix_team_game_stats_opponent",
        "team_game_stats",
        ["opponent_team_id", "game_id"],
        unique=False,
    )
    op.create_index(
        "ix_team_game_stats_team", "team_game_stats", ["team_id", "game_id"], unique=False
    )
    op.create_table(
        "player_game_stats",
        sa.Column("game_id", sa.String(length=16), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("opponent_team_id", sa.BigInteger(), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("did_play", sa.Boolean(), nullable=False),
        sa.Column("minutes_seconds", sa.SmallInteger(), nullable=True),
        sa.Column("points", sa.SmallInteger(), nullable=True),
        sa.Column("assists", sa.SmallInteger(), nullable=True),
        sa.Column("blocks", sa.SmallInteger(), nullable=True),
        sa.Column("steals", sa.SmallInteger(), nullable=True),
        sa.Column("field_goals_attempted", sa.SmallInteger(), nullable=True),
        sa.Column("field_goals_made", sa.SmallInteger(), nullable=True),
        sa.Column("field_goal_percentage", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("three_pointers_attempted", sa.SmallInteger(), nullable=True),
        sa.Column("three_pointers_made", sa.SmallInteger(), nullable=True),
        sa.Column("three_point_percentage", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("free_throws_attempted", sa.SmallInteger(), nullable=True),
        sa.Column("free_throws_made", sa.SmallInteger(), nullable=True),
        sa.Column("free_throw_percentage", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("defensive_rebounds", sa.SmallInteger(), nullable=True),
        sa.Column("offensive_rebounds", sa.SmallInteger(), nullable=True),
        sa.Column("total_rebounds", sa.SmallInteger(), nullable=True),
        sa.Column("personal_fouls", sa.SmallInteger(), nullable=True),
        sa.Column("turnovers", sa.SmallInteger(), nullable=True),
        sa.Column("plus_minus", sa.SmallInteger(), nullable=True),
        sa.Column("availability_comment", sa.Text(), nullable=True),
        sa.Column("starting_position", sa.String(length=8), nullable=True),
        sa.CheckConstraint(
            "starting_position IS NULL OR starting_position IN ('G', 'F', 'C')",
            name="ck_player_stats_starting_position",
        ),
        sa.CheckConstraint(
            "(did_play AND minutes_seconds IS NOT NULL AND points IS NOT NULL "
            "AND assists IS NOT NULL AND total_rebounds IS NOT NULL) OR "
            "(NOT did_play AND minutes_seconds IS NULL AND points IS NULL "
            "AND assists IS NULL AND total_rebounds IS NULL)",
            name="ck_player_stats_played_semantics",
        ),
        sa.CheckConstraint(
            "field_goal_percentage IS NULL OR "
            "(field_goal_percentage >= 0 AND field_goal_percentage <= 1)",
            name="ck_player_stats_fg_pct",
        ),
        sa.CheckConstraint(
            "field_goals_made IS NULL OR field_goals_made BETWEEN 0 AND field_goals_attempted",
            name="ck_player_stats_fg_counts",
        ),
        sa.CheckConstraint(
            "free_throw_percentage IS NULL OR "
            "(free_throw_percentage >= 0 AND free_throw_percentage <= 1)",
            name="ck_player_stats_ft_pct",
        ),
        sa.CheckConstraint(
            "free_throws_made IS NULL OR free_throws_made BETWEEN 0 AND free_throws_attempted",
            name="ck_player_stats_ft_counts",
        ),
        sa.CheckConstraint(
            "minutes_seconds IS NULL OR minutes_seconds >= 0", name="ck_player_stats_minutes"
        ),
        sa.CheckConstraint("team_id <> opponent_team_id", name="ck_player_stats_distinct_teams"),
        sa.CheckConstraint(
            "three_point_percentage IS NULL OR "
            "(three_point_percentage >= 0 AND three_point_percentage <= 1)",
            name="ck_player_stats_3p_pct",
        ),
        sa.CheckConstraint(
            "three_pointers_made IS NULL OR "
            "three_pointers_made BETWEEN 0 AND three_pointers_attempted",
            name="ck_player_stats_3p_counts",
        ),
        sa.CheckConstraint(
            "total_rebounds IS NULL OR total_rebounds = offensive_rebounds + defensive_rebounds",
            name="ck_player_stats_rebounds",
        ),
        sa.ForeignKeyConstraint(
            ["game_id", "team_id"],
            ["team_game_stats.game_id", "team_game_stats.team_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opponent_team_id"],
            ["teams.team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.player_id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "player_id"),
    )
    op.create_index(
        "ix_player_game_stats_opponent",
        "player_game_stats",
        ["opponent_team_id", "game_id"],
        unique=False,
    )
    op.create_index(
        "ix_player_game_stats_player", "player_game_stats", ["player_id", "game_id"], unique=False
    )
    op.create_index(
        "ix_player_game_stats_team", "player_game_stats", ["team_id", "game_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_player_game_stats_team", table_name="player_game_stats")
    op.drop_index("ix_player_game_stats_player", table_name="player_game_stats")
    op.drop_index("ix_player_game_stats_opponent", table_name="player_game_stats")
    op.drop_table("player_game_stats")
    op.drop_index("ix_team_game_stats_team", table_name="team_game_stats")
    op.drop_index("ix_team_game_stats_opponent", table_name="team_game_stats")
    op.drop_table("team_game_stats")
    op.drop_index("ix_games_season_type_date", table_name="games")
    op.drop_index(op.f("ix_games_season_id"), table_name="games")
    op.drop_index("ix_games_home_team_date", table_name="games")
    op.drop_index(op.f("ix_games_game_type"), table_name="games")
    op.drop_index(op.f("ix_games_game_date"), table_name="games")
    op.drop_index("ix_games_away_team_date", table_name="games")
    op.drop_table("games")
    op.drop_table("teams")
    op.drop_index("ix_players_name", table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
